[package]
name = "paekli-py"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[lib]
name = "paekli_py"
crate-type = ["cdylib"]

[dependencies]
paekli-core = { version = "0.1.0", path = "../paekli-core" }
pyo3 = "0.20.0"
