name: GitHub Pages
on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  pages:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: |
          rustup target add wasm32-unknown-unknown
          cd paekli-web
          wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.19.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          ./trunk build --release --public-url /rw-test
          mv dist ../docs
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@invalid.local"
          git checkout -b gh-pages
          git add ../docs
          git commit --message "GitHub Pages Deployment"
          git push --force --set-upstream origin gh-pages
